
#ifndef BAR_FOREGROUND
#define BAR_FOREGROUND "#bbbbbb"
#endif

#ifndef BAR_BACKGROUND
#define BAR_FOREGROUND "#222222"
#endif



#ifndef BATTERY_FOREGROUND_LOW
#define BATTERY_FOREGROUND_LOW "#bbbbbb"
#endif

#ifndef BATTERY_FOREGROUND_MED
#define BATTERY_FOREGROUND_MED "#bbbbbb"
#endif

#ifndef BATTERY_FOREGROUND_HIGH
#define BATTERY_FOREGROUND_HIGH "#bbbbbb"
#endif

#ifndef BATTERY_BACKGROUND_LOW
#define BATTERY_BACKGROUND_LOW "#222222"
#endif

#ifndef BATTERY_BACKGROUND_MED
#define BATTERY_BACKGROUND_MED "#222222"
#endif

#ifndef BATTERY_BACKGROUND_HIGH
#define BATTERY_BACKGROUND_HIGH "#222222"
#endif

#ifndef BATTERY_CUTOF_HIGH
#define BATTERY_CUTOF_HIGH 80
#endif

#ifndef BATTERY_CUTOF_LOW
#define BATTERY_CUTOF_LOW 20
#endif

#ifndef WMNAME_FOREGROUND
#define WMNAME_FOREGROUND "#bbbbbb"
#endif

#ifndef WMNAME_BACKGROUND
#define WMNAME_BACKGROUND "#222222"
#endif

#ifndef CLOCK_FOREGROUND
#define CLOCK_FOREGROUND "#bbbbbb"
#endif

#ifndef CLOCK_BACKGROUND
#define CLOCK_BACKGROUND "#222222"
#endif

#ifndef NET_UP_FOREGROUND
#define NET_UP_FOREGROUND "#bbbbbb"
#endif

#ifndef NET_UP_BACKGROUND
#define NET_UP_BACKGROUND "#222222"
#endif

#ifndef NET_DOWN_FOREGROUND
#define NET_DOWN_FOREGROUND "#bbbbbb"
#endif

#ifndef NET_DOWN_BACKGROUND
#define NET_DOWN_BACKGROUND "#222222"
#endif

#ifndef NETIFACE
#define NETIFACE "eth0"
#endif

#ifndef WEATHER_FOREGROUND
#define WEATHER_FOREGROUND "#eee"
#endif

#ifndef WEATHER_BACKGROUND
#define WEATHER_BACKGROUND "#222"
#endif



